name: Sarah Brabazon
favicon: null
layout_spectrum: 0.7018323426600546
typography_spectrum: 0.11675248737446964
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.10535284806974232
  lightness: 0.43275506352074444
  saturation: 0.592915405984968
  rhythmicContrast: 0.3001757829915732
purpose: []
